# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-09 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invetorylist',
            name='keypair',
        ),
        migrations.AddField(
            model_name='invetorylist',
            name='keypair',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='KeyPair',
        ),
    ]
