# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-09 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgmt', '0002_auto_20191209_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceid', models.CharField(max_length=100)),
                ('instancetype', models.CharField(max_length=100)),
                ('amiid', models.CharField(max_length=100)),
                ('instancestatus', models.CharField(max_length=100)),
                ('az', models.CharField(max_length=100)),
                ('privateip', models.CharField(max_length=100)),
                ('privatednsname', models.CharField(max_length=100)),
                ('publicdnsname', models.CharField(max_length=100)),
                ('publicip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='InvetoryList',
        ),
        migrations.AddField(
            model_name='inventory',
            name='keypair',
            field=models.ManyToManyField(blank=True, to='inventorymgmt.KeyPair'),
        ),
    ]
